language: php

php:
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer update -n --prefer-dist $COMPOSER_FLAGS
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.0/coveralls.phar

before_script:
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/phpcs --standard=ruleset.xml ./src
  - vendor/bin/phan -m checkstyle -o build/logs/checkstyle.cs

after_script:
  - php coveralls.phar -v --exclude-no-stmt
